version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - dokploy-network
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    volumes:
      - /opt/dokploy/volumes/cynadev-api/public/images:/var/www/html/public/images

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: php bin/console messenger:consume async --time-limit=3600 --memory-limit=256M --env=prod
    networks:
      - dokploy-network
    environment:
      APP_ENV: prod
      APP_DEBUG: 0

networks:
  dokploy-network:
    external: true