<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260320103804 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cart (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BA388B79395C3F3 ON cart (customer_id)');
        $this->addSql('CREATE TABLE cart_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, cart_id INT DEFAULT NULL, product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BEF484451AD5CDBF ON cart_items (cart_id)');
        $this->addSql('CREATE INDEX IDX_BEF484454584665A ON cart_items (product_id)');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B79395C3F3 FOREIGN KEY (customer_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF484451AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id)');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF484454584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE homepage ALTER bannerctalink SET NOT NULL');
        $this->addSql('ALTER TABLE product_plan ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE product_plan ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_plan_product_id RENAME TO IDX_50B279DC4584665A');
        $this->addSql('DROP INDEX idx_promo_code_string');
        $this->addSql('ALTER TABLE promo_code ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE promo_code ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE promo_code ALTER value TYPE DOUBLE PRECISION');
        $this->addSql('ALTER INDEX promo_code_code_key RENAME TO UNIQ_3D8C939E77153098');
        $this->addSql('ALTER TABLE stock ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE stock ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_stock_product_id RENAME TO IDX_4B3656604584665A');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cart DROP CONSTRAINT FK_BA388B79395C3F3');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF484451AD5CDBF');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF484454584665A');
        $this->addSql('DROP TABLE cart');
        $this->addSql('DROP TABLE cart_items');
        $this->addSql('ALTER TABLE homepage ALTER bannerctalink DROP NOT NULL');
        $this->addSql('ALTER TABLE product_plan ALTER id SET DEFAULT nextval(\'product_plan_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE product_plan ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_50b279dc4584665a RENAME TO idx_plan_product_id');
        $this->addSql('ALTER TABLE promo_code ALTER id SET DEFAULT nextval(\'promo_code_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE promo_code ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE promo_code ALTER value TYPE NUMERIC(10, 2)');
        $this->addSql('CREATE INDEX idx_promo_code_string ON promo_code (code)');
        $this->addSql('ALTER INDEX uniq_3d8c939e77153098 RENAME TO promo_code_code_key');
        $this->addSql('ALTER TABLE stock ALTER id SET DEFAULT nextval(\'stock_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE stock ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_4b3656604584665a RENAME TO idx_stock_product_id');
    }
}
