<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260317161106 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE homepage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titleprincipal VARCHAR(255) NOT NULL, titlewordbold VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NOT NULL, firstbutton VARCHAR(255) NOT NULL, secondbutton VARCHAR(255) NOT NULL, bannercentral VARCHAR(255) NOT NULL, subtitlebanner VARCHAR(255) NOT NULL, bannercta VARCHAR(255) NOT NULL, pubtitle VARCHAR(255) NOT NULL, pubdesc VARCHAR(255) NOT NULL, pubbutton VARCHAR(255) NOT NULL, publinkbutton VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE homepage');
    }
}
