name: CI API Symfony

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, zip
          tools: composer:v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # On installe sans les scripts pour éviter que Symfony ne plante
      # pendant l'installation des dépendances.
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --no-scripts

      # On lance les scripts Symfony manuellement une fois que le système est prêt
      - name: Run Symfony production scripts
        run: |
          php bin/console cache:clear --env=prod --no-debug
          php bin/console cache:warmup --env=prod --no-debug

  sonar-scan:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.organization=cynadev 
            -Dsonar.projectKey=CynaDev_cynadev-api