name: Deploy Symfony API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        env:
          # On récupère le contenu du secret GitHub
          PROD_ENV_CONTENT: ${{ secrets.PROD_ENV_FILE }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PROD_ENV_CONTENT # On injecte la variable pour le script
          run: echo "${{ secrets.ENV_FILE }}" > .env
          script: |
            cd /home/devuser/cynadev/cynadev-api/
            
            # 1. On récupère les dernières modifications du code
            git pull origin main

            # 2. On supprime le cache, les logs, les dépendances et l'ancien .env
            rm -rf var/cache/* var/log/* vendor/ .env

            # 3. On crée le nouveau fichier .env avec le contenu du Secret GitHub
            echo "$PROD_ENV_CONTENT" > .env

            # 4. On installe les dépendances (tout neuf)
            composer install --no-dev --optimize-autoloader --no-interaction
            
            # 5. On exécute les migrations et on prépare le cache
            php bin/console doctrine:migrations:migrate --no-interaction --env=prod
            php bin/console cache:clear --env=prod
            php bin/console cache:warmup --env=prod